### ISSUE TITLE
脚注の追加

### ISSUE THREAD

**Issue by abap34** [abap34/almo#129]
脚注の機能がないのであるとよさそう。

1. 適当な構文で脚注の表示とidを振れるようにする (例: `これは Aによる研究 [^a_research] により示された。`)
2. id に対応する脚注の文を書くと、末尾に生成される。例: `[a_reserch]: example.com`
3. もとの文に連番が振られる。

構文は既存の仕様の調査が必要そう。

**Comment by abap34** [comment]
一部のパース結果が全体に影響するようなものは `Reader` クラスで `set_meta_data` を使って管理しています。
https://github.com/abap34/almo/blob/dd09f27e829f6c08a9562155300d96dd40dd0e24/src/reader.hpp#L52-L68


たとえば、「実行可能なコードブロックがソースコード全体に一つでもあるか？」という情報も管理しているんですが、(これをすることで不要な場合読み込みをスキップして高速化できます)

ここ
https://github.com/abap34/almo/blob/dd09f27e829f6c08a9562155300d96dd40dd0e24/src/syntax/Judge.hpp#L257

 で `set_meta_data` を使って管理しています。

一旦書き出しの処理は後で考えることにして、文法を定義 → パーサを書いて `Reader` に持たせる までやってみるといいかもしれません (作業移ってくれるのであれば assign します :eye:

**Comment by potato167** [comment]
わかりました
作業したいと思います。

**Comment by abap34** [comment]
assign しました！

**Comment by potato167** [comment]
"[^" + expr + "]:" + hoge という形に分解したいんですけど、それをどうやるかがわかっておりません

**Comment by noya2ruler** [comment]
正規表現の使い方がわからない、という話ですか？
